comment_index:
    path:     /
    defaults: { _controller: "ForumBundle:CommentForum:index" }
    methods:  GET

comment_show:
    path:     /{id}/show
    defaults: { _controller: "ForumBundle:CommentForum:show" }
    methods:  GET

comment_new:
    path:     /new
    defaults: { _controller: "ForumBundle:CommentForum:new" }
    methods:  [GET, POST]

comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "ForumBundle:CommentForum:edit" }
    methods:  [GET, POST]

comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "ForumBundle:CommentForum:delete" }
    methods:  DELETE
