njareb:
    resource: "@NjarebBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    # app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

