<?php

namespace TicketBundle\Repository;

/**
 * ReportIssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportIssueRepository extends \Doctrine\ORM\EntityRepository
{
}
