<?php

namespace TicketBundle\Repository;

/**
 * Report_issueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Report_issueRepository extends \Doctrine\ORM\EntityRepository
{
}
